spring:
  application:
    name: Flight-service
  data:
    mongodb:
      host: localhost
      port: 27017
      database: accountsdb
server:
  port: 2222
  
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
      
zuul:
  routes:
    flights: /Flight-service/**