server:
  port: 9090

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:5555/eureka/

zuul:
  #Service will be mapped under the /api URI
  prefix: /api
#  Uncomment to disable auto-registering all services read from Eureka
#  ignoredServices: '*'
  routes:
    test:
      path: /redirect/**
      url: http://google.com
    accounts-service:
      path: /accounts/**
      url: http://localhost:5559
    balance-service:
      path: /balance/**
      serviceId: ACCOUNT-SERVICE
    static:
      path: /static/**

spring:
  application:
    name: zuul-server